In [1]:
import numpy as np

In [2]:
arr=[int(i) for i in input().split()]
arr=np.array(arr)
arr

1 3 9 0 2


array([1, 3, 9, 0, 2])

In [3]:
print(np.__version__)

1.18.5


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
#tuple to create array
arr=np.array((5,6,7,8))
arr

array([5, 6, 7, 8])

In [7]:
#create a 0-D array
a=np.array(20)
a

array(20)

In [8]:
#create a 1-D array
x=np.array([6,7,8,9,0])
x

array([6, 7, 8, 9, 0])

In [9]:
#create a 2-D array
n=np.array([[7,8,9],[5,5,4]])
print(n)

[[7 8 9]
 [5 5 4]]


In [12]:
#create a 3-D array
arr=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[0,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 5 6]]]


In [13]:
#Check Number Of Dimensions
a=np.array(20)
b=np.array([6,2,7,4,5])
c=np.array([[1, 9, 3], [7, 5, 6]])
d=np.array([[[1, 4, 3], [4, 7, 6]], [[1, 8, 3], [4, 9, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
n = np.array([[1,2,6,4,5], [6,7,11,9,10]])
print('Print 3rd Element Of 2nd dimension:', n[1, 3])

Print 3rd Element Of 2nd dimension: 9


In [16]:
p = np.array([[1,2,7,4,5], [6,7,12,9,10]])
print('2nd Last Element From 1st dimension: ', p[0, -2])

2nd Last Element From 1st dimension:  4


In [17]:
m = np.array([1, 2, 3, 4, 5, 6, 7])
print(m[0:4:1])

[1 2 3 4]


In [18]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
